import type { Metadata } from 'next';
import './globals.css';
import Provider from './provider';
export const metadata: Metadata = {
  title: 'Blinkmate',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
